[api]
# port = "8080"
port = "8081"
[database]
# host = "postgres"
host = "localhost"
port = "5432"
user = "freterapido"
pass = "freterapidopsdw"
name = "freterapido-api"
[run]
type = "debug"
[freterapido_api]
base_url = "sp.freterapido.com/api"
api_version = "v3"
registered_number = "25438296000158"
token = "1d52a9b6b78cf07b08586152459a5c90"
platform_code = "5AKVkHqCn"
zipcode = "29161376"
