version: "3.8"

services:
  postgres:
    image: postgres:16.1-alpine3.19
    container_name: db-freterapido-api
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: freterapido
      POSTGRES_PASSWORD: freterapidopsdw
      POSTGRES_DB: freterapido-api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d gopos" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    driver: local