version: "3.3"



services:
  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres
    networks:
      - freterapidoapplication
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: freterapido
      POSTGRES_PASSWORD: freterapidopsdw
      POSTGRES_DB: freterapido-api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d gopos" ]
      interval: 5s
      timeout: 5s
      retries: 5
  freterapido-api:
    image: freterapido-api:latest
    container_name: freterapido_api
    networks:
      - freterapidoapplication
    ports:
      - 8080:8080
    restart: always

networks:
  freterapidoapplication:
    name: freterapidoapplication
    driver: bridge

volumes:
  postgres:
    driver: local